export interface Artwork {
  id: string;
  title: string;
  desc: string;
  longDesc: string;
  size: string;
  price: string;
  material: string;
  status: "DISPONIBLE" | "NO DISPONIBLE";
  src: string;
  type: "lamina" | "lienzo";
  gallery: string[];
}

export const artworks: Artwork[] = [
  {
    id: "flecha-de-el-rompido",
    title: "Flecha de El Rompido",
    desc: "Acrílico sobre lienzo con técnica de raspado",
    longDesc: "Pieza dinámica que captura una regata mediante la repetición de formas. El fondo turquesa saturado aporta frescura y luminosidad, mientras que los trazos blancos, aplicados con técnica de raspado, enfatizan la verticalidad y el movimiento de las embarcaciones en grupo.",
    material: "Acrílico sobre lienzo",
    size: "40 x 60 x 3.5 cm",
    price: "100 €",
    status: "DISPONIBLE",
    src: "/images/el-rompido-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/el-rompido-2.jpg",
      "/images/el-rompido-3.jpg",
      "/images/el-rompido-4.jpg",
    ],
  },
  {
    id: "cenida-en-punta-umbria",
    title: "Ceñida en Punta Umbría",
    desc: "Estudio sobre la técnica pura de navegación",
    longDesc: "Una composición estilizada que captura la técnica pura de la navegación. El ángulo de la vela sugiere una ceñida cerrada, luchando contra el viento. Sobre un fondo azul oscuro absoluto, emerge una vela blanca con texturas que sugieren el desgaste del viento. Incluye un detalle sutil de salpicaduras en rojo en el cuadrante superior, rompiendo la sobriedad de la pieza con un acento de color orgánico.",
    material: "Acrílico sobre lienzo",
    size: "40 x 80 cm",
    price: "100 €",
    status: "DISPONIBLE",
    src: "/images/cenida-1.jpg",
    type: "lienzo",
    gallery: ["/images/cenida-1.jpg", "/images/cenida-2.jpg", "/images/cenida-3.jpg"],
  },
  {
    id: "regata-de-poniente",
    title: "Regata de Poniente",
    desc: "Composición horizontal con superposición de velas",
    longDesc: "Composición horizontal con acumulación de planos y superposición de velas, generando profundidad mediante contraste alto en blanco sobre azul marino. La textura compuesta por arena del parque de Doñana y el gesto seco evocan el viento de poniente.",
    material: "Acrílico sobre lienzo",
    size: "80 x 60 x 4 cm",
    price: "150 €",
    status: "DISPONIBLE",
    src: "/images/regata-poniente-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/regata-poniente-1.jpg",
      "/images/regata-poniente-2.jpg",
      "/images/regata-poniente-3.jpg",
    ],
  },
  {
    id: "hispaniard",
    title: "Hispaniard",
    desc: "Registro cromático con vela en tono vino",
    longDesc: "Cambio de registro cromático con una base neutra y una vela en tono vino que concentra todo el peso visual.",
    material: "Acrílico sobre lienzo",
    size: "50 x 70 cm",
    price: "120 €",
    status: "DISPONIBLE",
    src: "/images/hispaniard-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/hispaniard-1.jpg",
      "/images/hispaniard-2.jpg",
      "/images/hispaniard-3.jpg",
      "/images/hispaniard-4.jpg",
    ],
  },
  {
    id: "almagra-de-poniente",
    title: "Almagra de Poniente",
    desc: "Rojo óxido evocando los atardeceres de Huelva",
    longDesc: "El fondo rojo óxido evoca los atardeceres de Huelva, tecnica sobre madera.",
    material: "Acrílico sobre madera",
    size: "30 x 40 cm",
    price: "40 €",
    status: "DISPONIBLE",
    src: "/images/almagra-1.jpg",
    type: "lienzo",
    gallery: ["/images/almagra-1.jpg", "/images/almagra-2.jpg", "/images/almagra-3.jpg"],
  },
  {
    id: "verde-estero",
    title: "Verde Estero",
    desc: "Paleta reducida en verde profundo",
    longDesc: "Paleta reducida en verde profundo con blancos desgastados, donde el espacio negativo cobra protagonismo.",
    material: "Acrílico sobre lienzo",
    size: "40 x 60 cm",
    price: "100 €",
    status: "DISPONIBLE",
    src: "/images/verde-estero-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/verde-estero-1.jpg",
      "/images/verde-estero-2.jpg",
      "/images/verde-estero-3.jpg",
      "/images/verde-estero-4.jpg",
      "/images/verde-estero-5.jpg",
    ],
  },
  {
    id: "bahia-en-carrera",
    title: "Bahía en Carrera",
    desc: "Vibración lumínica sobre fondo azul",
    longDesc: "La pincelada es más suelta y fragmentada, generando vibración lumínica sobre el fondo azul. Los detalles en naranja funcionan como anclajes visuales.",
    material: "Acrílico sobre lienzo",
    size: "50 x 50 cm",
    price: "100 €",
    status: "DISPONIBLE",
    src: "/images/bahia-carrera-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/bahia-carrera-1.jpg",
      "/images/bahia-carrera-2.jpg",
      "/images/bahia-carrera-3.jpg",
    ],
  },
  {
    id: "flota-de-sal",
    title: "Flota de Sal",
    desc: "Díptico rítmico",
    longDesc: "Composición doble que juega con la repetición rítmica de las velas blancas sobre el azul profundo. El rojo funciona como un acento de color que recorre ambas piezas.",
    material: "Acrílico sobre lienzo",
    size: "40 x 30 cm (por cada pieza)",
    price: "180 €",
    status: "DISPONIBLE",
    src: "/images/flota-sal-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/flota-sal-1.jpg",
      "/images/flota-sal-2.jpg",
      "/images/flota-sal-3.jpg",
      "/images/flota-sal-4.jpg",
    ],
  },
  {
    id: "taleo",
    title: "Taleo",
    desc: "Formato vertical con dirección ascendente",
    longDesc: "Formato vertical que enfatiza la dirección ascendente de la vela principal, construida con una pincelada larga y dominante.",
    material: "Acrílico sobre lienzo",
    size: "30 x 60 cm",
    price: "100 €",
    status: "NO DISPONIBLE",
    src: "/images/taleo-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/taleo-1.jpg",
      "/images/taleo-2.jpg",
      "/images/taleo-3.jpg",
    ],
  },
  {
    id: "regata-juan-sebastian-el-cano",
    title: "Regata Juan Sebastián el Cano",
    desc: "Esencia de la mítica regata canaria",
    longDesc: "Captura la esencia de la mítica regata con pinceladas enérgicas sobre un fondo azul profundo, evocando la fuerza y la tradición náutica.",
    material: "Acrílico sobre lienzo",
    size: "60 x 60 cm",
    price: "180 €",
    status: "NO DISPONIBLE",
    src: "/images/regata-cano-1.jpg",
    type: "lienzo",
    gallery: [
      "/images/regata-cano-1.jpg",
      "/images/regata-cano-2.jpg",
      "/images/regata-cano-3.jpg",
    ],
  },
];
